CREATE DATABASE IF NOT EXISTS `TUB_GAMING` DEFAULT CHARACTER SET utf8;
USE `TUB_GAMING`;

DROP TABLE IF EXISTS `DATA`;

CREATE TABLE `DATA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` varchar(45) NOT NULL,
  `PLAYER_ID` varchar(45) DEFAULT NULL,
  `GAME_ID` varchar(45) NOT NULL,
  `GAME_VERSION` varchar(45) NOT NULL,
  `VERIFICATION_CODE` varchar(45) NOT NULL,
  `PLAYING_DATE` varchar(45) DEFAULT NULL,
  `PLAYING_TIME` varchar(45) DEFAULT NULL,
  `STAT` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

GRANT SELECT,INSERT ON TUB_GAMING.* TO 'code'@'localhost';